### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by AtomSnow** [Protinon/Blender-rpc#10]
![image](https://user-images.githubusercontent.com/51972322/116519923-5950d400-a8d2-11eb-9940-5e8a39634394.png)

I cannot start the addon fsr

I downloaded the release, im using blender 2.77 from steam, maybe thats the issue?

**Comment by Protinon** [comment]
Please download the addon from the "Releases" section

**Comment by AtomSnow** [comment]
> Please download the addon from the "Releases" section

but i did that...

**Comment by Protinon** [comment]
No you didn't, the image of your issue is because you cloned the repository. There are numerous other closed issues with the exact same problem. I even left one open because it was so common.

I can clearly see in the image what the issue is, the last line says it's trying to import from `Blender-rpc-master` which only happens when cloned. You can test it right now by comparing the cloned and released folder names.

You need to delete the addon you installed and re-install from the released version.

**Comment by AtomSnow** [comment]
I downloaded the release and still the same issue, i could even put video somewhere me doing it...
