### ISSUE TITLE
Suggestion about new features

### ISSUE THREAD

**Issue by GimmeHat** [Protinon/Blender-rpc#3]
I have a few suggestions on how to improve this addon.

1. Simulation bake status (for example: fluid baking);
    Number of the baking frame (like rendering status) _(for example: 220 of 250)_.
    And name of the simulation.

2. Compositing/Shading/Modeling/Sculpting etc. tabs status.

**Comment by Protinon** [comment]
1. A good idea, but due to limitations in Blender's Python API it's not possible. Nothing in there signifies a change in Blender's state when a bake job is initialized/completed. 

2. This is most likely the next feature. Though I doubt how many people actually change between workspaces when editing projects (at least, I don't...). 

Thanks for the suggestions!
