### ISSUE TITLE
Shows "Single Frame" when rendering animation to images

### ISSUE THREAD

**Issue by SwitchBL8** [Protinon/Blender-rpc#9]
Rendering a big animation is always (well, if you're smart) done to separate images instead of a movie format. The add-on shows "Single Frame" and not the actual frame it's rendering at the moment. Would be helpful if it did to remotely monitor progress (by me and others).

**Comment by SwitchBL8** [comment]
Okay, I need to rephrase that, it does show the frame number I'm rendering but it's the relative frame number. Is there a way to show the absolute frame number that is rendering (for example: I'm rendering frame 1111 of a total of 6000, but that is in a batch that started at 1100 and ends in 1200, so now it says frame 11 of 100).

**Comment by Protinon** [comment]
You say "Would be helpful if it did to remotely monitor progress", but showing an absolute frame number would not be more informative to users. From your example, say there are total 6000 frames, and the current render batch is 1100 to 1200:

- If discord shows "1120 of 6000", that wouldn't be helpful at all, since you won't be rendering up to frame 6000.
- If discord shows "1120 of 1200", it would be deceitful, as you actually haven't rendered 1100 frames up until now, you started there.
- If discord shows "20 of 100" (current behavior), it shows how many you've rendered and how many you have left to go. Less info than you might like, but 0 confusion to other discord users, which this addon is focused on.

**Comment by SwitchBL8** [comment]
I get the reasoning behind it. Still, I would love to see the absolute frame number implemented, Configurable or so, since not everybody will use it. But in our group, we KNOW how many frames there are, and the xth frame of y batchsize is not informative enough, since several people take ranges of frames to render. Let's say well all get 100 frames, we could all end up having a status of "Frame 10 of 100".

**Comment by Protinon** [comment]
Sorry, I can't see it being useful outside your case. While your group is all aware of the frame ranges, this addon is for a general Discord status.

However, you can fork this addon and make the change for your group. At line 237 (function name getFrameRange) is the code that generates the frame range numbers. I just added info to the README to get the repository working as a Blender addon.

**Comment by SwitchBL8** [comment]
Okay. No problem dude. Thanks for looking into it.
